config/routes.rb
Rails.application.routes.draw do
 
  resources :events do	
  	resources :attendees, controller: 'event_attendees'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
	belongs_to :event
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
	before_action :set_event


	def index
	  @attendees = @event.attendees
	end

	def show
	  @attendee = @event.attendees.find( params[:id] )
	end

	def new
	  @attendee = @event.attendees.build
	end

	def create
	  @attendee = @event.attendees.build( attendee_params )
	  if @attendee.save
	    redirect_to event_attendees_url( @event )
	  else
	    render :action => :new
	  end
	end

	def edit
	  @attendee = @event.attendees.find( params[:id] )
	end

	def update
	  @attendee = @event.attendees.find( params[:id] )

	  if @attendee.update( attendee_params )
	    redirect_to event_attendees_url( @event )
	  else
	    render :action => :edit
	  end

	end

	def destroy
	  @attendee = @event.attendees.find( params[:id] )
	  @attendee.destroy

	  redirect_to event_attendees_url( @event )
	end



	private
	def set_event
		@event = Event.find(params[:event_id])
	end
	
	def attendee_params
		params.require(:attendee).permit(:name)
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :descrption, :is_public, :capacity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/event_attendees/edit.html.erb
<%= form_for @attendee, :url => event_attendee_path(@event, @attendee), :html => { :method => :patch } do |f| %>

   <%= f.text_field :name %>
   <%= f.submit %>

<% end %>

app/views/event_attendees/index.html.erb
<h2><%= @event.name %>: Attendee List</h2>


<ul>
<% @attendees.each do |attendee| %>
	<li>
	  <%= attendee.name %>
	  <%= link_to 'show', event_attendee_path(@event, attendee) %>
	  <%= link_to 'edit', edit_event_attendee_path(@event, attendee) %>
	  <%= link_to 'destroy', event_attendee_path(@event, attendee),
	                            :method => :delete %>
	</li>
<% end %>

</ul>

<%= link_to 'new attendee', new_event_attendee_path(@event) %>
<br>
<%= link_to 'back to event index', events_path %>

app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>
   <%= f.text_field :name %>
   <%= f.submit %>
<% end %>

app/views/event_attendees/show.html.erb
<h2><%= @event.name %></h2>

<%= @attendee.name %>
<br>

<%= link_to 'Back to index', event_attendees_path(@event) %>

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :descrption %>
    <%= f.text_area :descrption %>
  </div>

  <div class="field">
    <%= f.label :is_public %>
    <%= f.check_box :is_public %>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Descrption</th>
      <th>Is public</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.descrption %></td>
        <td><%= event.is_public %></td>
        <td><%= event.capacity %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Attendee List', event_attendees_path(event) %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Descrption:</strong>
  <%= @event.descrption %>
</p>

<p>
  <strong>Is public:</strong>
  <%= @event.is_public %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @event.capacity %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AcRailsEvent</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>